name: disk

out_base: output/

gas: true
species : 12CO # Possible choices: 12CO, 13CO, C18O. Future may include HCN, etc...
transition: 3-2 # J =

grid:
  nr: 128
  ntheta: 46 # if mirrored about the equator, total of 64
  nphi: 1
  r_in: 0.1 # [AU] # Inner edge of model grid
  r_out: 2000. # [AU] # Outer edge of model grid

# Are there any channels of the dataset to exclude? If so, provide them here, indexed from 1.
# exclude: [35, 36, 37, 38]

# What type of model will we be fitting? This also affects which parameters to include.
model : nuker # choices of {standard, truncated, vertical, cavity, etc..}

# parameters, either used for model synthesis or visualization. Be careful that all of these are Float64 and not Int
parameters:
  M_star: 1.03 # [M_sun] stellar mass
  r_c: 80.00 # [AU] characteristic radius
  T_10: 91.85 # [K] temperature at 10 AU
  q: 0.5 # temperature gradient exponent
  gamma: -1.5 # surface density gradient within r_c (negative values yield holes)
  log_alpha : 0.5 # log10 sharpness of transition (10^0.1 = smooth, 10^1.2 = sharp)
  beta : 7.0 # gradient power law outside r_c (~7)
  log_M_gas: 3.0 # [M_Sun] disk mass of gas
  ksi: 0.2 # [km/s] microturbulence
  dpc: 145. # [pc] distance
  incl: 45.0 # [degrees] inclination
  PA: 152.0 # [degrees] position angle
  vel: 0.00 # [km/s]
  mu_RA: 0.00 # [arcsec] centroid location
  mu_DEC: 0.00 # [arcsec]

# List the parameters you want fixed here.
fix_params: ["dpc"]

# The HDF5 file containing the visibilities
data_file: data.hdf5

# Image setup
size_arcsec : 60.0 # [arcsec] full width/height of image
npix: 256

# Starting positions of walkers
pos0: pos0.npy

# MCMC setup
samples: 1
loops: 1

# Some parameters that may be helpful for making more realistic channel map plots of the model.
# You will likely need to change these to correspond to the parameters of your observation.
beam :
  rms : 0.1 # Jy/beam
  BMAJ: 0.9 # arcsec
  BMIN: 0.9 # arcsec
  BPA: 1.0 # degrees east of North of the semi-major axis.
